### ISSUE TITLE
Roadmap and To-Do

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/meeting-media-manager#2781]
Here's a simple tracker of things I'd like to do eventually. I accept code contributions and suggestions!

---

## To-Do / Wishlist

- [ ] Optimize sqlite queries by specifying which columns to fetch
- [ ] #3746

## Done / Implemented

- [x] #4949
- [x] #4855 
- [x] #3479
- [x] Add e2e testing
- [x] For CO week, hide media instead of removing it completely
- [x] Implement past date media folder cleanup functions
- [x] #3653
- [x] #3750
- [x] #2770
- [x] #3481
- [x] Clean up UI based on feedback
- [x] Test migration from previous version at a KH
- [x] Prevent going to day when in past (additional media for example)
- [x] Show warning notification in existing version of M³ about upcoming update
- [x] Fix Chrome image drop
- [x] Fix song adding/loading UI
- [x] Compare existing strings and remove unneeded strings to allow updated translations on Crowdin
- [x] sircharlo/mmm-refactor#59
- [x] sircharlo/mmm-refactor#65
- [x] #3348
- [x] Add documentation website, built using VitePress and deployed to Github Pages
- [x] Make video fetching non-blocking (stream if not downloaded yet)
- [x] Add feature to include meeting songs in the background music
- [x] Fix the audio click when stopping media mid-play
- [x] Add public talk media logic
- [x] #2766 
- [x] Fix/tweak action island popup placement
- [x] Look into macOS full-screen toggle not having the desired behavior
- [x] #2571
- [x] #2302
- [x] #2768
- [x] Cache metadata-extracted thumbnails for faster loading

**Comment by mtdvlpr** [comment]
> Hi @sircharlo, we added a new page in the project in Figma called “Design review”, where we wrote some of the details along with images to make it clearer. Feel free to leave your additional comments there.

Any chance I can be added to that Figma file? I would love to see it and perhaps even contribute my thoughts on it.

**Comment by ux-git** [comment]
> Add a re-fetch button (in settings?) to force a refresh of scheduled media

What about adding the re-fetch button right in the Media sync window? For example one button for all ERROR media. This way it's really intuitive and allows to solve the problem right away _[by any brother at the computer]_ instead of investigating into the settings options _[and asking the specific brother who knows where to look at]_:

<img width="498" alt="Screenshot 2024-12-02 at 04 54 28" src="https://github.com/user-attachments/assets/18b7b683-4b65-43c3-8ea8-a77801f36408">

**Comment by ux-git** [comment]
> What about adding the re-fetch button right in the Media sync window?

1. Additionally, to solve the missing media anxiety in cases when re-initiating the sync won't help (e.g. media not yet available), M³ could show the meeting date for each media in the 'errors' section.Either on hover or with a smaller description-like text underneath.

This will let users see that the error is not for today's meeting, but rather a few weeks later, so they won't have to worry. Plus, the media naming is not humanly-readable, making it harder to troubleshoot errors by searching for a iifa12-p2.mp4 in the Library for example. But having the date will allow you to simply go to that date on a mobile device, and find out that one of the media items is not yet available.

2. Also, maybe some kind of "Try later" button would make sense in this setup. Let's say, a missing media is not yet available and it's 4 weeks away. Then by clicking "Try later" the media will try to sync in 7 days once again, but at least it won't show the error state on the sync button, giving more peace of mind to AV operators.

**Comment by sircharlo** [comment]
> > What about adding the re-fetch button right in the Media sync window?
> 
> 1. Additionally, to solve the missing media anxiety in cases when re-initiating the sync won't help (e.g. media not yet available), M³ could show the meeting date for each media in the 'errors' section.Either on hover or with a smaller description-like text underneath.
> 
> This will let users see that the error is not for today's meeting, but rather a few weeks later, so they won't have to worry. Plus, the media naming is not humanly-readable, making it harder to troubleshoot errors by searching for a iifa12-p2.mp4 in the Library for example. But having the date will allow you to simply go to that date on a mobile device, and find out that one of the media items is not yet available.
> 
> 2. Also, maybe some kind of "Try later" button would make sense in this setup. Let's say, a missing media is not yet available and it's 4 weeks away. Then by clicking "Try later" the media will try to sync in 7 days once again, but at least it won't show the error state on the sync button, giving more peace of mind to AV operators.

Let me know what you thnk of the changes to the download popup in the next beta!
