### ISSUE TITLE
Checklist before releasing 22.11.0

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#627]
Some things that need to be tested again before releasing:
- [x] Malagasy works without dayjs error
- [x] Image zoom and pan works correctly and preview and media window always show the same (https://github.com/sircharlo/meeting-media-manager/commit/3399c9a32be61de8a6f7cdf412efbcc7bafe7f8f)
- [x] Everything works correctly on Windows 32-bit platform (https://github.com/sircharlo/meeting-media-manager/commit/b92db40c75e7bac09c4b7e2395948498ae1e62a7)
- [x] mp3 to mp4 conversion works correctly (https://github.com/sircharlo/meeting-media-manager/pull/629/commits/412238bdefec285beef2f105e17103abfede015c)

**Comment by sircharlo** [comment]
Hm. 

`Error: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0`

![image](https://user-images.githubusercontent.com/1275666/200190468-bbbfc7fc-062a-4bc5-a0dc-b9ed4e9d3a2c.png)

**Comment by sircharlo** [comment]
> WebAssembly.instantiate(): expected magic word

Perhaps related to https://github.com/WebAssembly/spec/issues/1031

**Comment by sircharlo** [comment]
Duh. Ran the equivalent `prebuild` commands.

**Comment by mtdvlpr** [comment]
I tested Malagasy and image zoom/pan. No issues on my end.

**Comment by sircharlo** [comment]
> 

Check out my new commit, it improves the display of images when the aspect ratio isn't exactly 16:9.

**Comment by sircharlo** [comment]
MP3 to MP4 worked fine, ffmpeg download and ran the conversion. The progress bar didn't disappear, but not a major issue IMO.

**Comment by sircharlo** [comment]
> MP3 to MP4 worked fine, ffmpeg download and ran the conversion. The progress bar didn't disappear, but not a major issue IMO.

This is what is displayed after the conversion finishes. No errors in console.

![image](https://user-images.githubusercontent.com/1275666/200193401-0615c5dd-063f-4342-bd51-7d65e952fd12.png)

**Comment by mtdvlpr** [comment]
Strange that it doesn't go to 100%. After it reaches 100%, it will reset and dissapear

**Comment by mtdvlpr** [comment]
Found it. It doesn't call setProgress in the mp3 if branch

**Comment by sircharlo** [comment]
I'll test the following on Win32:
- [ ] sync
- [ ] cong sync
- [ ] cong upload
- [ ] cong delete
- [ ] image convert of PDFs
- [ ] MP4 convert of images and MP3s
- [ ] media playback window
- [ ] zoom/pan
- [ ] background music

**Comment by mtdvlpr** [comment]
> I'll test the following on Win32:

Awesome! Afterwards I think we're good to go with the release :)
The Sentry issues that are still open can't be pinned down to a fix (yet), so I'll set them to resolved in next release.

**Comment by sircharlo** [comment]
For some reason, `lff` isn't extracting properly. Other publications are, but not `lff`. Hmm.

**Comment by sircharlo** [comment]
Are we possibly hitting some sort of memory issue on low-memory systems, since we're `loadAsync`'ing the zip files into memory before extracting them?

**Comment by mtdvlpr** [comment]
Might be related to [this](https://stackoverflow.com/questions/70736831/err-error-end-of-data-reached-data-length-0-asked-index-4-corrupted-zip)

**Comment by sircharlo** [comment]
> Might be related to [this](https://stackoverflow.com/questions/70736831/err-error-end-of-data-reached-data-length-0-asked-index-4-corrupted-zip)

I'll wait for the build to finish and try it out with the updated try/catches

**Comment by sircharlo** [comment]
Here's something interesting. The JWPUB file doesn't seem to be downloaded properly.

![image](https://user-images.githubusercontent.com/1275666/200196009-4973df8c-8660-4106-b771-bd61d66affbd.png)

**Comment by mtdvlpr** [comment]
Ah okay. We're missing a check to see if the jwpub file is valid.

**Comment by sircharlo** [comment]
I deleted the 0kb JWPUB file to see what happens.

1. Click blue button
2. JWPUB file starts getting downloaded
3. Zipper attempts to extract JWPUB file before download is complete
4. JWPUB file seems to change size alot, almost as if it's being downloaded twice simultaneously and overwriting the same file?!
5. Error message
6. Windows folder now shows the whole JWPUB file

**Comment by mtdvlpr** [comment]
That would be in line with the stackoverflow answer:
> I believe you would get this error after you stop your execution in between, i.e when the file is getting updated and this would corrupt the excel file.

**Comment by mtdvlpr** [comment]
Maybe because of the async execution the lff file is referenced multiple times and therefore download multiple times at the same time. You could look at the network tab to see if that's the case

**Comment by sircharlo** [comment]
> Maybe because of the async execution the lff file is referenced multiple times and therefore download multiple times at the same time. You could look at the network tab to see if that's the case

Bingo.

![image](https://user-images.githubusercontent.com/1275666/200196406-b77befe6-bf5d-4494-905e-6dfc33d1d659.png)

**Comment by sircharlo** [comment]
Both files get downloaded at the same time, overwriting the same file. Zipper on the first execution because the download from the second execution is still happening.

**Comment by sircharlo** [comment]
I can confirm that running the sync once the lff file has been downloaded (by a previous sync) results in a correctly unzipped lff folder.

**Comment by sircharlo** [comment]
Makes sense that this is a new issue, as pre-refactor publications were downloaded sequentially. If a pub already existed (because it had just been downloaded, for example), then the download was simply skipped.

This is a scenario that would need to be accounted for, as I could see this causing errors in real-world scenarios, especially on newer installations that don't have publications like lff cached yet.

**Comment by sircharlo** [comment]
Would there be a way to modify `downloadIfRequired` to:

- check if a publication id has been queued for download

If it has: 

- resolve when the existing, queued download is complete

If it hasn't: 

- add the publication id to the queue, and
- start the download 
- resolve when the download is complete

**Comment by mtdvlpr** [comment]
Working on it

**Comment by mtdvlpr** [comment]
see #634

**Comment by mtdvlpr** [comment]
It seems to work, because I'm now only seeing one call after clearing the cache and no errors

**Comment by mtdvlpr** [comment]
@sircharlo, can you check if it also works on win32?

**Comment by mtdvlpr** [comment]
I'm signing off. Time to go to sleep😴

**Comment by sircharlo** [comment]
> @sircharlo, can you check if it also works on win32?

Negative, unfortunately.

![image](https://user-images.githubusercontent.com/1275666/200204743-03de62e4-4884-4c0c-a6b8-a6b376cc463f.png)

Probably related to the low amount of memory of 32-bit systems (https://stackoverflow.com/questions/45920143/how-to-handle-array-buffer-allocation-failed-in-nodejs)

**Comment by sircharlo** [comment]
Slight regression introduced, see https://github.com/sircharlo/meeting-media-manager/pull/634#issuecomment-1304952468

**Comment by mtdvlpr** [comment]
> Slight regression introduced, see [#634 (comment)](https://github.com/sircharlo/meeting-media-manager/pull/634#issuecomment-1304952468)

Fixed in #635

**Comment by mtdvlpr** [comment]
I got my virtual Windows 32-bit machine working too! Everything seems to work, except converting mp3 to mp4. That goes wrong every time. The error is now caught and a human friendly warning is given. Since converting mp3 to mp4 is a real edge case, and it only goes wrong on 32-bit machines, I'd say forget about it.

**Comment by sircharlo** [comment]
> I got my virtual Windows 32-bit machine working too! Everything seems to work, except converting mp3 to mp4. That goes wrong every time. The error is now caught and a human friendly warning is given. Since converting mp3 to mp4 is a real edge case, and it only goes wrong on (low-memory?) 32-bit machines, I'd say forget about it.

Even worse, it works for me in Win32 😆
But agreed, not the end of the world.

**Comment by mtdvlpr** [comment]
Haha, then it's probably a memory thing.

**Comment by mtdvlpr** [comment]
I'd say we're good to go then

**Comment by mtdvlpr** [comment]
It's easier for you, since you can push directly to master. I'd have to create a pull request which I'm not sure has the desired outcome.

**Comment by mtdvlpr** [comment]
@sircharlo, so what happened is you wanted to push the release commit, but got blocked because you had to git pull first. Then when you pushed the merge commit got evaluated instead of the release commit, so no release workflow was executed. You'll have to do another chore(release)

**Comment by sircharlo** [comment]
> @sircharlo, so what happened is you wanted to push the release commit, but got blocked because you had to git pull first. Then when you pushed the merge commit got evaluated instead of the release commit, so no release workflow was executed. You'll have to do another chore(release)

Yeah my bad, I redid it and it worked after. :)

**Comment by sircharlo** [comment]
Weirdly enough, the autoupdate didn't work for me until I deleted the `%localappdata%\meeting-media-manager-updater` folder.

**Comment by sircharlo** [comment]
Nah, I didn't build on my machine at all. Must be a glitch with my setup, I wouldn't worry about it too much
