### ISSUE TITLE
[Feature]: Improve jw.org in M3 feature

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#761]
_Originally posted by @sircharlo in https://github.com/sircharlo/meeting-media-manager/issues/672#issuecomment-1328268004_
     
List of improvements to implement

- [x] Solve desync actions (log in, change lang) #776
- [x] Scale and zoom preview for accurate representation (#1484)
- [x] Show mouse pointer on media window (#1389)
- [x] Solve links (online library / jw hub) opening new browser tabs #776
- [ ] Mirror input (ie., when typing something in search field, languages field, etc)
- [ ] Mirror text selection
- [ ] Zoom in/out

**Comment by mtdvlpr** [comment]
I also think some might find it more useful if the web view had a sort of visual indication of where the mouse pointer is. Sometimes, the point of these demos is to say "click here, click there", and that might be harder for some to understand if they don't see where the pointer is.

**Comment by mtdvlpr** [comment]
- [ ] Solve desync actions (log in, change lang)
- [ ] scale and zoom preview for accurate representation
- [ ] Show mouse pointer on media window

**Comment by mtdvlpr** [comment]
Bump

**Comment by mtdvlpr** [comment]
@sircharlo, nice work!

**Comment by e-Feitosa** [comment]
When opening the JW.ORG window, I miss the window opening maximized. Here in the tests, a small JW window opens on top of the M3, see below how it opens with the screen extended (image 1). Note: On the second screen (TV/MONITOR/ZOOM) the screen is OK. A suggestion (image 2) (I don't know how much work this would take) would be to duplicate what the mouse does on the main screen to the second screen, in the example, on the PC screen, I selected the text, however, on the projected screen, only captures the movement of the course (red circle)

**IMAGE 1**
<picture>
![image](https://user-images.githubusercontent.com/90984283/219206928-97ebf9d3-c5da-4f0b-8b45-9c0457ec851a.png)
</picture>


**IMAGE 2**
![image](https://user-images.githubusercontent.com/90984283/219207796-d4afc348-630c-475a-8df9-9f5004bc3e0a.png)

**Comment by mtdvlpr** [comment]
@e-Feitosa, we'll add the `mirror selected text` to the todo list. As for maximizing th website controller window, the intended behaviour is this:

If the media window is fullscreen, maximize the window.
If not fullscreen, try to match the media window height and width.

Is this not what's happening?

**Comment by mtdvlpr** [comment]
@sircharlo which of the many width/height properties did you use? BrowserWindow.getbounds(), window.innerWidth, window.document.scrollWidth?

**Comment by sircharlo** [comment]
> @sircharlo which of the many width/height properties did you use? BrowserWindow.getbounds(), window.innerWidth, window.document.scrollWidth?

`BrowserWindow.getContentSize()`, since that gives the actual internal size (mediaWin doesn't have borders, so `BrowserWindow.getSize()` is the same as `BrowserWindow.getContentSize()`, but for the controller window the internal size differs by a few pixels).

Also, I think the forced 16:9 aspect ratio of the controller window needs to be re-thought, since 16:9 doesn't account for the controller window's title bar...

**Comment by mtdvlpr** [comment]
@sircharlo, we may not have to. Take a look at #1484 :)

**Comment by mtdvlpr** [comment]
Bump

**Comment by alanfermtz** [comment]
is there a possibility to being able to zoom in and out?

**Comment by mtdvlpr** [comment]
@alanfermtz, we could look into it

**Comment by mtdvlpr** [comment]
Bump

**Comment by mtdvlpr** [comment]
Bump

**Comment by mtdvlpr** [comment]
Bump
