### ISSUE TITLE
[Docs]: Add new features

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#900]
The new features have been piling up, but the documentation is still at release 22.8.1. The new features should be documented as well, and the features that have been altered will have to be updated in the docs as well. Most changes are about the new settings, but some are always available, like the `open jw.org` feature in presentation mode. 

Some but not all todos:

- [x] Add note about enabling studio audio and stereo in Zoom
- [x] Describe missing settings in configuration page (#1453)
- [x] Describe open jw.org feature in present-media page (#1453)
- [x] Describe zoom-and-pan feature in present-media page (#1453)
- [x] Describe sorting feature in present-media page (#1453)
- [x] Describe last-minute song-picker in present-media page (#1453)

Preferably #899 should be finished first.

**Comment by mtdvlpr** [comment]
@sircharlo, all pages have now been optimized! Only the congregation-sync page has not been migrated fully (joaochris is busy with that). But this means we can start adding all the new features to the settings page and other pages. The only thing to keep in mind is when you update the English page in `/locales/_posts`, you have to copy paste the page content to the same page in `/_includes/posts`. The one in includes is the fallback page when a language has not been translated yet.

**Comment by mtdvlpr** [comment]
@sircharlo, I added the missing settings (that need explanation). If you could check my phrasing, that'd be great :)

**Comment by mtdvlpr** [comment]
@sircharlo, could you handle the `note about enabling studio audio and stereo in Zoom`? I don't know what you wanted to say about it.

**Comment by mtdvlpr** [comment]
@sircharlo, could you handle the `note about enabling studio audio and stereo in Zoom`? I don't know what you wanted to say about it.

**Comment by sircharlo** [comment]
> @sircharlo, could you handle the `note about enabling studio audio and stereo in Zoom`? I don't know what you wanted to say about it.

[Done](https://github.com/sircharlo/meeting-media-manager/commit/a066f81decb560bd0d7179be457e1477082494b4).
